export interface CharacterProfile {
  id: string;
  name: string;
  codename: string;
  role: string;
  department: 'Command' | 'Database' | 'Security' | 'Infrastructure' | 'Operations' | 'Network' | 'Telemetry' | 'Chaos' | 'Tactical';
  avatar: string;
  status: 'active' | 'in-call' | 'standby' | 'dispatch';
  audioDistance?: number;
  inRange?: boolean;
  voiceActive?: boolean;
  clearanceLevel: 'L4 - Commander' | 'L3 - Principal' | 'L2 - Specialist' | 'L1 - Operator';
  specialty: string;
  bio: string;
  colorAccent: string;
}

export const RESPONDER_ROSTER: CharacterProfile[] = [
  {
    id: 'eric',
    name: 'Eric',
    codename: 'NIGHT_COMMANDER',
    role: 'Incident Commander',
    department: 'Command',
    avatar: '/characters/Eric.png',
    status: 'active',
    clearanceLevel: 'L4 - Commander',
    specialty: 'Distributed War-Room Authority & Consensus Approval',
    bio: 'Lead Commander of OpsWArd EOC. Holds consensus quorum keys and authorizes emergency failover playbooks.',
    colorAccent: '#ec4899',
    voiceActive: true,
  },
  {
    id: 'james',
    name: 'James',
    codename: 'POSTGRES_TITAN',
    role: 'Principal Database Architect',
    department: 'Database',
    avatar: '/characters/James.png',
    status: 'in-call',
    clearanceLevel: 'L3 - Principal',
    specialty: 'High-Availability Sharding, WAL Replication & Rollback',
    bio: 'Veteran DB architect managing multi-region cluster replicas and zero-data-loss failover procedures.',
    colorAccent: '#a855f7',
    voiceActive: false,
  },
  {
    id: 'miria',
    name: 'Miria',
    codename: 'CRYPTO_VALKYRIE',
    role: 'Lead Cryptographic Security Auditor',
    department: 'Security',
    avatar: '/characters/Miria.png',
    status: 'active',
    clearanceLevel: 'L3 - Principal',
    specialty: 'Zero-Trust Authentication, Key Vaults & Threat Isolation',
    bio: 'Security lead specializing in preventing Byzantine actors, rogue injections, and perimeter breaches.',
    colorAccent: '#06b6d4',
    voiceActive: false,
  },
  {
    id: 'nuying',
    name: 'NuYing',
    codename: 'OPS_CHRONOMANCER',
    role: 'Site Reliability Operations Lead',
    department: 'Operations',
    avatar: '/characters/NuYing.png',
    status: 'active',
    clearanceLevel: 'L3 - Principal',
    specialty: 'SLO/SLA Budgeting, Kubernetes Autoscaling & Traffic Drains',
    bio: 'Orchestrates rapid containerized failovers and maintains 99.999% uptime across production clusters.',
    colorAccent: '#38bdf8',
    voiceActive: true,
  },
  {
    id: 'george',
    name: 'George',
    codename: 'ARCHITECT_PRIME',
    role: 'Lead Systems Architect',
    department: 'Infrastructure',
    avatar: '/characters/George.png',
    status: 'active',
    clearanceLevel: 'L3 - Principal',
    specialty: 'Distributed Consensus (Raft/Paxos) & Microservices Mesh',
    bio: 'Architect of the core distributed state machine and multi-datacenter consensus backbone.',
    colorAccent: '#3b82f6',
    voiceActive: false,
  },
  {
    id: 'tony',
    name: 'Tony',
    codename: 'TERRAFORM_CORE',
    role: 'Infrastructure & Cloud Lead',
    department: 'Infrastructure',
    avatar: '/characters/Tony.png',
    status: 'active',
    clearanceLevel: 'L2 - Specialist',
    specialty: 'BGP Routing, Bare-Metal Scaling & SDN Provisioning',
    bio: 'Oversees physical data center nodes, network backplanes, and low-latency interconnects.',
    colorAccent: '#8b5cf6',
    voiceActive: false,
  },
  {
    id: 'santi',
    name: 'Santi',
    codename: 'TELEMETRY_ORACLE',
    role: 'DevOps & Telemetry Specialist',
    department: 'Telemetry',
    avatar: '/characters/Santi.png',
    status: 'in-call',
    clearanceLevel: 'L2 - Specialist',
    specialty: 'High-Throughput OpenTelemetry Streams & Anomaly Detection',
    bio: 'Monitors real-time Prometheus alert metrics and automated Dead Letter Queue dispatch pipelines.',
    colorAccent: '#f43f5e',
    voiceActive: true,
  },
  {
    id: 'rose',
    name: 'Rose',
    codename: 'SRE_VALKYRIE',
    role: 'Senior Reliability Engineer',
    department: 'Operations',
    avatar: '/characters/Rose.png',
    status: 'active',
    clearanceLevel: 'L2 - Specialist',
    specialty: 'Circuit Breaking, Backoff Retries & Distributed Tracing',
    bio: 'Specialist in dynamic rate-limiting and preventing cascading upstream service failures.',
    colorAccent: '#f97316',
    voiceActive: false,
  },
  {
    id: 'rinda',
    name: 'Rinda',
    codename: 'NET_SPECTRUM',
    role: 'Network Operations Lead',
    department: 'Network',
    avatar: '/characters/Rinda.png',
    status: 'active',
    clearanceLevel: 'L2 - Specialist',
    specialty: 'Anycast DNS, Edge CDN Routing & DDoS Mitigation',
    bio: 'Guardian of global egress and ingress edge gateways, neutralizing volumetric network attacks.',
    colorAccent: '#eab308',
    voiceActive: false,
  },
  {
    id: 'yanto',
    name: 'Yanto',
    codename: 'CHAOS_ENGINEER',
    role: 'Chaos & Disaster Recovery Lead',
    department: 'Chaos',
    avatar: '/characters/Yanto.png',
    status: 'active',
    clearanceLevel: 'L3 - Principal',
    specialty: 'Chaos Injection, Split-Brain Testing & Resilience Drills',
    bio: 'Tests system boundaries by injecting network partitions, node failures, and clock drift anomalies.',
    colorAccent: '#dc2626',
    voiceActive: true,
  },
  {
    id: 'theresa',
    name: 'Theresa',
    codename: 'PROTOCOL_GUARDIAN',
    role: 'Security Protocol Officer',
    department: 'Security',
    avatar: '/characters/Theresa.png',
    status: 'standby',
    clearanceLevel: 'L2 - Specialist',
    specialty: 'HSM Cryptography, Mutual TLS & Audit Verification',
    bio: 'Maintains tamper-proof consensus audit trails and cryptographic incident records.',
    colorAccent: '#6366f1',
    voiceActive: false,
  },
  {
    id: 'jesfer_normal',
    name: 'Jesfer',
    codename: 'SHADOW_ANALYST',
    role: 'Threat Intelligence Analyst',
    department: 'Security',
    avatar: '/characters/Jesfer Normal Form.png',
    status: 'active',
    clearanceLevel: 'L2 - Specialist',
    specialty: 'Malware Forensics & Zero-Day Incident Tracking',
    bio: 'Deep forensic analyst monitoring threat actor signatures and suspicious network telemetry.',
    colorAccent: '#64748b',
    voiceActive: false,
  },
  {
    id: 'jesfer_clown',
    name: 'Jesfer (Overdrive)',
    codename: 'ROGUE_SIMULATOR',
    role: 'Adversary Simulation Specialist',
    department: 'Chaos',
    avatar: '/characters/Jesfer Clown Form.png',
    status: 'dispatch',
    clearanceLevel: 'L3 - Principal',
    specialty: 'Red-Team Penetration & Byzantine Fault Emulation',
    bio: 'Emulates advanced persistent threats (APT) to stress-test OpsWArd automated compensation sagas.',
    colorAccent: '#d946ef',
    voiceActive: false,
  },
  {
    id: 'alex',
    name: 'Alex',
    codename: 'EDGE_ROUTER',
    role: 'Edge Infrastructure Engineer',
    department: 'Network',
    avatar: '/characters/Alex.png',
    status: 'standby',
    clearanceLevel: 'L1 - Operator',
    specialty: 'QUIC Protocol & WebRTC Media Edge Nodes',
    bio: 'Optimizes spatial media stream routing across regional WebRTC SFU mesh clusters.',
    colorAccent: '#0ea5e9',
    voiceActive: false,
  },
  {
    id: 'andri',
    name: 'Andri',
    codename: 'STREAM_PIPELINE',
    role: 'Kafka Event Broker Engineer',
    department: 'Telemetry',
    avatar: '/characters/Andri.png',
    status: 'active',
    clearanceLevel: 'L2 - Specialist',
    specialty: 'Partition Balancing, DLQ Routing & Replay Buffers',
    bio: 'Ensures zero event loss across millions of concurrent telemetry streams and alert queues.',
    colorAccent: '#14b8a6',
    voiceActive: false,
  },
  {
    id: 'budi',
    name: 'Budi',
    codename: 'STORAGE_SENTINEL',
    role: 'Distributed Storage Specialist',
    department: 'Infrastructure',
    avatar: '/characters/Budi.png',
    status: 'standby',
    clearanceLevel: 'L1 - Operator',
    specialty: 'Ceph Object Stores & NVMe Cache Clustering',
    bio: 'Maintains durable block storage arrays and distributed file systems across fault domains.',
    colorAccent: '#84cc16',
    voiceActive: false,
  },
  {
    id: 'christ',
    name: 'Christ',
    codename: 'KUBE_OVERSEER',
    role: 'Kubernetes Cluster Engineer',
    department: 'Operations',
    avatar: '/characters/Christ.png',
    status: 'active',
    clearanceLevel: 'L2 - Specialist',
    specialty: 'StatefulSet Recovery & CNI Mesh Diagnostics',
    bio: 'Resolves CrashLoopBackOff incidents and network policy isolates in live clusters.',
    colorAccent: '#0284c7',
    voiceActive: false,
  },
  {
    id: 'dzuky',
    name: 'Dzuky',
    codename: 'MESH_NAVIGATOR',
    role: 'Service Mesh Specialist',
    department: 'Network',
    avatar: '/characters/Dzuky.png',
    status: 'in-call',
    clearanceLevel: 'L2 - Specialist',
    specialty: 'Istio Envoy Proxies & mTLS Traffic Encryption',
    bio: 'Tunes sidecar proxy routing tables and traffic splitting for canary deployments.',
    colorAccent: '#f59e0b',
    voiceActive: true,
  },
  {
    id: 'enjidiren',
    name: 'Enjidiren',
    codename: 'REDIS_ACCELERATOR',
    role: 'In-Memory Cache Specialist',
    department: 'Database',
    avatar: '/characters/Enjidiren.png',
    status: 'standby',
    clearanceLevel: 'L1 - Operator',
    specialty: 'Redis Sentinel Failover & Memory Tier Optimization',
    bio: 'Maintains sub-millisecond query caches and session state replication clusters.',
    colorAccent: '#e11d48',
    voiceActive: false,
  },
  {
    id: 'fanisa',
    name: 'Fanisa',
    codename: 'METRIC_SENTINEL',
    role: 'Alert Policy Engineer',
    department: 'Telemetry',
    avatar: '/characters/Fanisa.png',
    status: 'active',
    clearanceLevel: 'L1 - Operator',
    specialty: 'Grafana Dashboards & Anomaly Threshold Rules',
    bio: 'Designs precision alert trigger policies to eliminate alert fatigue and detect P0 anomalies.',
    colorAccent: '#ec4899',
    voiceActive: false,
  },
  {
    id: 'helina',
    name: 'Helina',
    codename: 'AUDIT_CHRONICLER',
    role: 'Compliance & Audit Specialist',
    department: 'Security',
    avatar: '/characters/Helina.png',
    status: 'standby',
    clearanceLevel: 'L1 - Operator',
    specialty: 'SOC2 Immutability & Consensus State Snapshots',
    bio: 'Verifies tamper-evident audit logs generated during high-severity disaster recovery playbooks.',
    colorAccent: '#a855f7',
    voiceActive: false,
  },
  {
    id: 'lemma',
    name: 'Lemma',
    codename: 'QUANT_ANALYST',
    role: 'Performance Optimization Engineer',
    department: 'Operations',
    avatar: '/characters/Lemma.png',
    status: 'active',
    clearanceLevel: 'L2 - Specialist',
    specialty: 'Kernel BPF Tracing & Latency Profiling',
    bio: 'Profiles eBPF kernel network stacks to identify micro-bottlenecks in production pipelines.',
    colorAccent: '#10b981',
    voiceActive: false,
  },
  {
    id: 'melinda',
    name: 'Melinda',
    codename: 'INGRESS_VALKYRIE',
    role: 'API Gateway Engineer',
    department: 'Network',
    avatar: '/characters/Melinda.png',
    status: 'active',
    clearanceLevel: 'L2 - Specialist',
    specialty: 'Kong/Traefik Ingress & Dynamic Load Balancing',
    bio: 'Ensures smooth traffic distribution and circuit breaking across ingress gateway clusters.',
    colorAccent: '#06b6d4',
    voiceActive: false,
  },
  {
    id: 'olimar',
    name: 'Olimar',
    codename: 'SECRETS_VAULT',
    role: 'Secrets & Identity Specialist',
    department: 'Security',
    avatar: '/characters/Olimar.png',
    status: 'standby',
    clearanceLevel: 'L1 - Operator',
    specialty: 'HashiCorp Vault & Dynamic Credential Rotation',
    bio: 'Manages automated rotation of database credentials and API tokens during compromised states.',
    colorAccent: '#6366f1',
    voiceActive: false,
  },
  {
    id: 'wilson_model',
    name: 'Wilson Model',
    codename: 'CYBER_AVATAR',
    role: 'AI Incident Copilot & Virtual Agent',
    department: 'Tactical',
    avatar: '/characters/Wilson Model.png',
    status: 'active',
    clearanceLevel: 'L4 - Commander',
    specialty: 'Automated Root-Cause Synthesis & Decision Guidance',
    bio: 'Autonomous tactical AI assisting responders by synthesizing live telemetry and proposing optimal playbooks.',
    colorAccent: '#f59e0b',
    voiceActive: true,
  },
  {
    id: 'yuki',
    name: 'Yuki',
    codename: 'FIRMWARE_CORE',
    role: 'Hardware & BMC Operations Specialist',
    department: 'Infrastructure',
    avatar: '/characters/Yuki.png',
    status: 'standby',
    clearanceLevel: 'L1 - Operator',
    specialty: 'IPMI/Redfish Remote Out-of-Band Recovery',
    bio: 'Executes hard power-cycle and firmware recovery for uncontactable physical hypervisors.',
    colorAccent: '#0ea5e9',
    voiceActive: false,
  },
];
